config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :lists do
    resources :items
  end
  root "lists#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list
  validates :name, presence: true
  validates :quantity, numericality: { greater_than: 0 }
end

app/models/list.rb
class List < ApplicationRecord
    has_many :items, dependent: :destroy
    validates :name, presence: true
    belongs_to :user
    
  end
  

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :lists, dependent: :destroy
        
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]

  # GET /items or /items.json
  def index
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @list = List.find(params[:list_id])
    @item = @list.items.build(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @list, notice: "Item was successfully added to the list." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    @list = List.find(params[:list_id])
    @item = @list.items.find(params[:id])

    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @list, notice: "Item was successfully updated." }
        format.js  
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.js   
      end
    end
  end
  

  # DELETE /items/1 or /items/1.json
  def destroy
    @list = List.find(params[:list_id])
    @item = @list.items.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to @list, status: :see_other, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:name, :quantity, :status, :list_id)
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_list, only: %i[ show edit update destroy ]
  before_action :correct_user, only: %i[ show edit update destroy ]

  # GET /lists or /lists.json
  def index
    @lists = current_user.lists
  end

  # GET /lists/1 or /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = current_user.lists.build
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists or /lists.json
  def create
    @list = current_user.lists.build(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: "List was successfully created." }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1 or /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: "List was successfully updated." }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1 or /lists/1.json
  def destroy
    @list.destroy

    respond_to do |format|
      format.html { redirect_to root_path, status: :see_other, notice: "List was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    def correct_user
      @list = current_user.lists.find_by(id: params[:id])
      redirect_to lists_path, notice: "Not authorized to access this list" if @list.nil?
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.require(:list).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/items/_form.html.erb
<%= form_with model: [@list, @list.items.build] do |form| %>
  <div style="display: flex; width: 100%; height: 40px; gap: 8px">
    <div class="field" style="display: flex; width: 100%">
      <%= form.text_field :name, placeholder: "Nome do item...", style: "width: 100%;" %>
    </div>

    <div class="field" style="display: flex;">
      <%= form.number_field :quantity, value: 1, min: 1, placeholder: "Quantidade..." %>
    </div>
      
      <%= form.hidden_field :status, value: false %>
    
    <div>
      <%= form.submit "Adicionar", style: "height: 100%; padding: 0px 8px" %>
    </div>
  </div>
<% end %>

app/views/items/_item.html.erb
<% if item.persisted? %> 
  <tr style="border: 1px solid gray" >
    <% if item.name.present? %>
      <td>
        <%= item.name %>
      </td>
    <% end %>

    <% if item.quantity.present? %>
      <td>
        <%= item.quantity %>
      </td>
    <% end %>

    <td>
      <%= form_with model: [item.list, item], url: list_item_path(item.list, item), method: :patch, remote: true do |form| %>

        <%= form.hidden_field :list_id, value: item.list.id %>
        <%= form.hidden_field :id, value: item.id %>
        <%= form.hidden_field :name, value: item.name %>
        <%= form.hidden_field :quantity, value: item.quantity %>

        <%= form.check_box :status, { checked: item.status }, true, false %>
        <%= form.hidden_field :status, value: false %>
    </td>
    <td>
        <%= form.submit "Update" %>
      <% end %>
    </td>
    <td>
      <%= button_to 'Del', list_item_path(item.list, item), method: :delete %>
    </td>
  </tr>
<% else %>
  <p>Item information is unavailable.</p>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Quantity</th>
      <th>Status</th>
      <th>List</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.quantity %></td>
        <td><%= item.status %></td>
        <td><%= item.list_id %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @item.quantity %>
</p>

<p>
  <strong>Status:</strong>
  <%= @item.status %>
</p>

<p>
  <strong>List:</strong>
  <%= @item.list_id %>
</p>

<%= link_to 'Edit', edit_list_item_path(@item.list, @item) %> |
<%= link_to 'Back', list_path(@item.list) %>

app/views/items/update.js.erb
$("#item_<%= @item.id %>").html("<%= j render @item %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShoppingListPrj</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav> 
      <% if user_signed_in? %> 
        <%= button_to 'Logout', destroy_user_session_path, method: :delete %> 
      <% else %> 
        <%= link_to 'Login', new_user_session_path %> 
        <%= link_to 'Sign up', new_user_registration_path %> 
      <% end %> 
    </nav>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: list) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.name %></td>
        <td><%= link_to 'Show', list %></td>
        <td><%= link_to 'Edit', edit_list_path(list) %></td>
        <td><%= button_to 'Destroy', list_path(list), method: :delete %> </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List', new_list_path %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container" style="display: flex; flex-direction: column; padding: 10vh 15vw">
  <div class="header" style="display: flex;align-items: top; width: 100%; justify-content: space-between;">
    <p style="margin: 0; font-weight: bold; font-size: 30px;">
      <%= @list.name %>
    </p>

    <div>
      <%= link_to 'Alterar Nome', edit_list_path(@list) %> |
      <%= link_to 'Voltar', lists_path %>
    </div>
  </div>
  

  <h2> Adicione um item: </h2>

  <%= render 'items/form', list: @list %>

  <h2> Itens: </h2>
  <% if @list.items.any? %>

    <table style="width: 100%">
      <thead>
        <tr>
          <th style="text-align: left; width: 100%">Nome</th>
          <th style="text-align: left; min-width: 100px">Quantidade</th>
          <th style="text-align: left; min-width: 60px">Status</th>
          <th style="text-align: left; min-width: 100px">Update</th>
          <th style="text-align: left; min-width: 60px">Delete</th>
        </tr>
      </thead>
      <tbody>
        <% @list.items.each do |item| %>
          <%= render 'items/item', item: item %>
        <% end %>
      </tbody>
    </table>
    
  <% else %>
    <p>No items added yet.</p>
  <% end %>

</div>